import { Montserrat } from "next/font/google";
import "./globals.css";
import Home from "./page";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Blog GitHub",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="pt-br">
      <body className={montserrat.className}> 
        <Home>{children}</Home>
        
      </body>
    </html>
  );
}
